### ISSUE TITLE
Fat pointer equality

### ISSUE THREAD

**Issue by jdonszelmann** [mbrubeck/by_address#5]
Since version 1.0.4, fat pointers are compared for equality using both their address and fat pointer value. For slices this is often what you want, you want to include their length in checks.

But I found a case similar to the one below where this is *not* the desired behavor.

```rust
trait A: Debug { fn test(&self) {} }
trait B: A { fn test2(&self) {}}

#[derive(Debug)]
struct Test {}
impl A for Test {}
impl B for Test {}

fn force_vtable<O: B>(v: &O) -> &dyn A {
    v
}

fn main() {
    let t = Test {};
    let tr1: &dyn A = &t;
    let tr2: &dyn A = force_vtable(&t);

    let a = ByAddress(tr1);
    let b = ByAddress(tr2);

    assert_eq!(a, b);
}
```
Here, both tr1 and tr2 are a &dyn A. They also live at the exact same address. I expected to use ByAddress to find that these two are equal.

However, force_vtable takes a generic argument that must implement B. That means that even though it returns &dyn A, the vtable *is actually different*. It contains pointers to B's functions too. That makes this assertion actually *fail*.

I hope this demonstrates that sometimes it can be useful to compare only by the address, not the whole fat pointer.

**Comment by jdonszelmann** [comment]
If you think by_address should support this case, I made a pull request fixing this issue by adding a ByThinAddr type that's in many ways similar to ByAddress, but compares thin pointers. (#6)

**Comment by VincentJousse** [comment]
@mbrubeck It would be very interesting to get this in a release. Do you plan to accept this ?
